/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerPolicyRouteImport } from './routes/volunteer-policy'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StaffingCompensationRouteImport } from './routes/staffing-compensation'
import { Route as SponsorAFamilyRouteImport } from './routes/sponsor-a-family'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as NonprofitStatusRouteImport } from './routes/nonprofit-status'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as HowFundsAreUsedRouteImport } from './routes/how-funds-are-used'
import { Route as HipaaRouteImport } from './routes/hipaa'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as FoodDrivesRouteImport } from './routes/food-drives'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as DonationPolicyRouteImport } from './routes/donation-policy'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CorporateSponsorshipsRouteImport } from './routes/corporate-sponsorships'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConflictOfInterestRouteImport } from './routes/conflict-of-interest'
import { Route as CommunityPartnersRouteImport } from './routes/community-partners'
import { Route as ChauntaesVoiceRouteImport } from './routes/chauntaes-voice'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BylawsRouteImport } from './routes/bylaws'
import { Route as BoardPortalRouteImport } from './routes/board-portal'
import { Route as BoardRouteImport } from './routes/board'
import { Route as BackToSchoolRouteImport } from './routes/back-to-school'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BoardPortalTasksRouteImport } from './routes/board-portal.tasks'
import { Route as BoardPortalNotificationsRouteImport } from './routes/board-portal.notifications'
import { Route as BoardPortalMessagesRouteImport } from './routes/board-portal.messages'
import { Route as BoardPortalEventsRouteImport } from './routes/board-portal.events'
import { Route as BoardPortalEdRouteImport } from './routes/board-portal.ed'
import { Route as BoardPortalDocumentsRouteImport } from './routes/board-portal.documents'
import { Route as BoardPortalCooRouteImport } from './routes/board-portal.coo'
import { Route as BoardPortalClerkRouteImport } from './routes/board-portal.clerk'
import { Route as BoardPortalCfoRouteImport } from './routes/board-portal.cfo'
import { Route as BoardPortalCalendarRouteImport } from './routes/board-portal.calendar'
import { Route as BoardPortalEventsIndexRouteImport } from './routes/board-portal.events.index'
import { Route as BoardPortalEdIndexRouteImport } from './routes/board-portal.ed.index'
import { Route as BoardPortalCooIndexRouteImport } from './routes/board-portal.coo.index'
import { Route as BoardPortalClerkIndexRouteImport } from './routes/board-portal.clerk.index'
import { Route as BoardPortalCfoIndexRouteImport } from './routes/board-portal.cfo.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as BoardPortalEventsVendorsRouteImport } from './routes/board-portal.events.vendors'
import { Route as BoardPortalEventsShoppingRouteImport } from './routes/board-portal.events.shopping'
import { Route as BoardPortalEventsReimbursementsRouteImport } from './routes/board-portal.events.reimbursements'
import { Route as BoardPortalEventsPurchaseRequestsRouteImport } from './routes/board-portal.events.purchase-requests'
import { Route as BoardPortalEventsInventoryRouteImport } from './routes/board-portal.events.inventory'
import { Route as BoardPortalEventsBudgetsRouteImport } from './routes/board-portal.events.budgets'
import { Route as BoardPortalEdWebsiteRouteImport } from './routes/board-portal.ed.website'
import { Route as BoardPortalEdVolunteersRouteImport } from './routes/board-portal.ed.volunteers'
import { Route as BoardPortalEdUsersRouteImport } from './routes/board-portal.ed.users'
import { Route as BoardPortalEdStaffRouteImport } from './routes/board-portal.ed.staff'
import { Route as BoardPortalEdSettingsRouteImport } from './routes/board-portal.ed.settings'
import { Route as BoardPortalEdReportsRouteImport } from './routes/board-portal.ed.reports'
import { Route as BoardPortalEdProgramsRouteImport } from './routes/board-portal.ed.programs'
import { Route as BoardPortalEdGrantsRouteImport } from './routes/board-portal.ed.grants'
import { Route as BoardPortalEdFinancialReportsRouteImport } from './routes/board-portal.ed.financial-reports'
import { Route as BoardPortalEdDonationsRouteImport } from './routes/board-portal.ed.donations'
import { Route as BoardPortalEdDocumentsRouteImport } from './routes/board-portal.ed.documents'
import { Route as BoardPortalEdBoardRouteImport } from './routes/board-portal.ed.board'
import { Route as BoardPortalEdBackToSchoolRouteImport } from './routes/board-portal.ed.back-to-school'
import { Route as BoardPortalEdAuditRouteImport } from './routes/board-portal.ed.audit'
import { Route as BoardPortalCooGapsRouteImport } from './routes/board-portal.coo.gaps'
import { Route as BoardPortalCooFeedbackRouteImport } from './routes/board-portal.coo.feedback'
import { Route as BoardPortalClerkVotesRouteImport } from './routes/board-portal.clerk.votes'
import { Route as BoardPortalClerkRecordsRouteImport } from './routes/board-portal.clerk.records'
import { Route as BoardPortalClerkPoliciesRouteImport } from './routes/board-portal.clerk.policies'
import { Route as BoardPortalClerkMinutesRouteImport } from './routes/board-portal.clerk.minutes'
import { Route as BoardPortalClerkFilingsRouteImport } from './routes/board-portal.clerk.filings'
import { Route as BoardPortalCfoReportsRouteImport } from './routes/board-portal.cfo.reports'
import { Route as BoardPortalCfoExpensesRouteImport } from './routes/board-portal.cfo.expenses'
import { Route as BoardPortalCfoDonationsRouteImport } from './routes/board-portal.cfo.donations'
import { Route as BoardPortalCfoBudgetRouteImport } from './routes/board-portal.cfo.budget'
import { Route as ApiPublicNotifyStaffRouteImport } from './routes/api/public/notify-staff'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const VolunteerPolicyRoute = VolunteerPolicyRouteImport.update({
  id: '/volunteer-policy',
  path: '/volunteer-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffingCompensationRoute = StaffingCompensationRouteImport.update({
  id: '/staffing-compensation',
  path: '/staffing-compensation',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorAFamilyRoute = SponsorAFamilyRouteImport.update({
  id: '/sponsor-a-family',
  path: '/sponsor-a-family',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const NonprofitStatusRoute = NonprofitStatusRouteImport.update({
  id: '/nonprofit-status',
  path: '/nonprofit-status',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowFundsAreUsedRoute = HowFundsAreUsedRouteImport.update({
  id: '/how-funds-are-used',
  path: '/how-funds-are-used',
  getParentRoute: () => rootRouteImport,
} as any)
const HipaaRoute = HipaaRouteImport.update({
  id: '/hipaa',
  path: '/hipaa',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodDrivesRoute = FoodDrivesRouteImport.update({
  id: '/food-drives',
  path: '/food-drives',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationPolicyRoute = DonationPolicyRouteImport.update({
  id: '/donation-policy',
  path: '/donation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateSponsorshipsRoute = CorporateSponsorshipsRouteImport.update({
  id: '/corporate-sponsorships',
  path: '/corporate-sponsorships',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictOfInterestRoute = ConflictOfInterestRouteImport.update({
  id: '/conflict-of-interest',
  path: '/conflict-of-interest',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPartnersRoute = CommunityPartnersRouteImport.update({
  id: '/community-partners',
  path: '/community-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauntaesVoiceRoute = ChauntaesVoiceRouteImport.update({
  id: '/chauntaes-voice',
  path: '/chauntaes-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BylawsRoute = BylawsRouteImport.update({
  id: '/bylaws',
  path: '/bylaws',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardPortalRoute = BoardPortalRouteImport.update({
  id: '/board-portal',
  path: '/board-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const BackToSchoolRoute = BackToSchoolRouteImport.update({
  id: '/back-to-school',
  path: '/back-to-school',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardPortalTasksRoute = BoardPortalTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => BoardPortalRoute,
} as any)
const BoardPortalNotificationsRoute =
  BoardPortalNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => BoardPortalRoute,
  } as any)
const BoardPortalMessagesRoute = BoardPortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => BoardPortalRoute,
} as any)
const BoardPortalEventsRoute = BoardPortalEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => BoardPortalRoute,
} as any)
const BoardPortalEdRoute = BoardPortalEdRouteImport.update({
  id: '/ed',
  path: '/ed',
  getParentRoute: () => BoardPortalRoute,
} as any)
const BoardPortalDocumentsRoute = BoardPortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => BoardPortalRoute,
} as any)
const BoardPortalCooRoute = BoardPortalCooRouteImport.update({
  id: '/coo',
  path: '/coo',
  getParentRoute: () => BoardPortalRoute,
} as any)
const BoardPortalClerkRoute = BoardPortalClerkRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => BoardPortalRoute,
} as any)
const BoardPortalCfoRoute = BoardPortalCfoRouteImport.update({
  id: '/cfo',
  path: '/cfo',
  getParentRoute: () => BoardPortalRoute,
} as any)
const BoardPortalCalendarRoute = BoardPortalCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => BoardPortalRoute,
} as any)
const BoardPortalEventsIndexRoute = BoardPortalEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardPortalEventsRoute,
} as any)
const BoardPortalEdIndexRoute = BoardPortalEdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardPortalEdRoute,
} as any)
const BoardPortalCooIndexRoute = BoardPortalCooIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardPortalCooRoute,
} as any)
const BoardPortalClerkIndexRoute = BoardPortalClerkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardPortalClerkRoute,
} as any)
const BoardPortalCfoIndexRoute = BoardPortalCfoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardPortalCfoRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardPortalEventsVendorsRoute =
  BoardPortalEventsVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => BoardPortalEventsRoute,
  } as any)
const BoardPortalEventsShoppingRoute =
  BoardPortalEventsShoppingRouteImport.update({
    id: '/shopping',
    path: '/shopping',
    getParentRoute: () => BoardPortalEventsRoute,
  } as any)
const BoardPortalEventsReimbursementsRoute =
  BoardPortalEventsReimbursementsRouteImport.update({
    id: '/reimbursements',
    path: '/reimbursements',
    getParentRoute: () => BoardPortalEventsRoute,
  } as any)
const BoardPortalEventsPurchaseRequestsRoute =
  BoardPortalEventsPurchaseRequestsRouteImport.update({
    id: '/purchase-requests',
    path: '/purchase-requests',
    getParentRoute: () => BoardPortalEventsRoute,
  } as any)
const BoardPortalEventsInventoryRoute =
  BoardPortalEventsInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => BoardPortalEventsRoute,
  } as any)
const BoardPortalEventsBudgetsRoute =
  BoardPortalEventsBudgetsRouteImport.update({
    id: '/budgets',
    path: '/budgets',
    getParentRoute: () => BoardPortalEventsRoute,
  } as any)
const BoardPortalEdWebsiteRoute = BoardPortalEdWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => BoardPortalEdRoute,
} as any)
const BoardPortalEdVolunteersRoute = BoardPortalEdVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => BoardPortalEdRoute,
} as any)
const BoardPortalEdUsersRoute = BoardPortalEdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => BoardPortalEdRoute,
} as any)
const BoardPortalEdStaffRoute = BoardPortalEdStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => BoardPortalEdRoute,
} as any)
const BoardPortalEdSettingsRoute = BoardPortalEdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BoardPortalEdRoute,
} as any)
const BoardPortalEdReportsRoute = BoardPortalEdReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => BoardPortalEdRoute,
} as any)
const BoardPortalEdProgramsRoute = BoardPortalEdProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => BoardPortalEdRoute,
} as any)
const BoardPortalEdGrantsRoute = BoardPortalEdGrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => BoardPortalEdRoute,
} as any)
const BoardPortalEdFinancialReportsRoute =
  BoardPortalEdFinancialReportsRouteImport.update({
    id: '/financial-reports',
    path: '/financial-reports',
    getParentRoute: () => BoardPortalEdRoute,
  } as any)
const BoardPortalEdDonationsRoute = BoardPortalEdDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => BoardPortalEdRoute,
} as any)
const BoardPortalEdDocumentsRoute = BoardPortalEdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => BoardPortalEdRoute,
} as any)
const BoardPortalEdBoardRoute = BoardPortalEdBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => BoardPortalEdRoute,
} as any)
const BoardPortalEdBackToSchoolRoute =
  BoardPortalEdBackToSchoolRouteImport.update({
    id: '/back-to-school',
    path: '/back-to-school',
    getParentRoute: () => BoardPortalEdRoute,
  } as any)
const BoardPortalEdAuditRoute = BoardPortalEdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => BoardPortalEdRoute,
} as any)
const BoardPortalCooGapsRoute = BoardPortalCooGapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => BoardPortalCooRoute,
} as any)
const BoardPortalCooFeedbackRoute = BoardPortalCooFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => BoardPortalCooRoute,
} as any)
const BoardPortalClerkVotesRoute = BoardPortalClerkVotesRouteImport.update({
  id: '/votes',
  path: '/votes',
  getParentRoute: () => BoardPortalClerkRoute,
} as any)
const BoardPortalClerkRecordsRoute = BoardPortalClerkRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => BoardPortalClerkRoute,
} as any)
const BoardPortalClerkPoliciesRoute =
  BoardPortalClerkPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => BoardPortalClerkRoute,
  } as any)
const BoardPortalClerkMinutesRoute = BoardPortalClerkMinutesRouteImport.update({
  id: '/minutes',
  path: '/minutes',
  getParentRoute: () => BoardPortalClerkRoute,
} as any)
const BoardPortalClerkFilingsRoute = BoardPortalClerkFilingsRouteImport.update({
  id: '/filings',
  path: '/filings',
  getParentRoute: () => BoardPortalClerkRoute,
} as any)
const BoardPortalCfoReportsRoute = BoardPortalCfoReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => BoardPortalCfoRoute,
} as any)
const BoardPortalCfoExpensesRoute = BoardPortalCfoExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => BoardPortalCfoRoute,
} as any)
const BoardPortalCfoDonationsRoute = BoardPortalCfoDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => BoardPortalCfoRoute,
} as any)
const BoardPortalCfoBudgetRoute = BoardPortalCfoBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => BoardPortalCfoRoute,
} as any)
const ApiPublicNotifyStaffRoute = ApiPublicNotifyStaffRouteImport.update({
  id: '/api/public/notify-staff',
  path: '/api/public/notify-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/back-to-school': typeof BackToSchoolRoute
  '/board': typeof BoardRoute
  '/board-portal': typeof BoardPortalRouteWithChildren
  '/bylaws': typeof BylawsRoute
  '/careers': typeof CareersRoute
  '/chauntaes-voice': typeof ChauntaesVoiceRoute
  '/community-partners': typeof CommunityPartnersRoute
  '/conflict-of-interest': typeof ConflictOfInterestRoute
  '/contact': typeof ContactRoute
  '/corporate-sponsorships': typeof CorporateSponsorshipsRoute
  '/documents': typeof DocumentsRoute
  '/donate': typeof DonateRoute
  '/donation-policy': typeof DonationPolicyRoute
  '/eligibility': typeof EligibilityRoute
  '/faq': typeof FaqRoute
  '/food-drives': typeof FoodDrivesRoute
  '/founder': typeof FounderRoute
  '/governance': typeof GovernanceRoute
  '/hipaa': typeof HipaaRoute
  '/how-funds-are-used': typeof HowFundsAreUsedRoute
  '/impact': typeof ImpactRoute
  '/insurance': typeof InsuranceRoute
  '/login': typeof LoginRoute
  '/nonprofit-status': typeof NonprofitStatusRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/referrals': typeof ReferralsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsor-a-family': typeof SponsorAFamilyRoute
  '/staffing-compensation': typeof StaffingCompensationRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/updates': typeof UpdatesRoute
  '/volunteer-policy': typeof VolunteerPolicyRoute
  '/board-portal/calendar': typeof BoardPortalCalendarRoute
  '/board-portal/cfo': typeof BoardPortalCfoRouteWithChildren
  '/board-portal/clerk': typeof BoardPortalClerkRouteWithChildren
  '/board-portal/coo': typeof BoardPortalCooRouteWithChildren
  '/board-portal/documents': typeof BoardPortalDocumentsRoute
  '/board-portal/ed': typeof BoardPortalEdRouteWithChildren
  '/board-portal/events': typeof BoardPortalEventsRouteWithChildren
  '/board-portal/messages': typeof BoardPortalMessagesRoute
  '/board-portal/notifications': typeof BoardPortalNotificationsRoute
  '/board-portal/tasks': typeof BoardPortalTasksRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/notify-staff': typeof ApiPublicNotifyStaffRoute
  '/board-portal/cfo/budget': typeof BoardPortalCfoBudgetRoute
  '/board-portal/cfo/donations': typeof BoardPortalCfoDonationsRoute
  '/board-portal/cfo/expenses': typeof BoardPortalCfoExpensesRoute
  '/board-portal/cfo/reports': typeof BoardPortalCfoReportsRoute
  '/board-portal/clerk/filings': typeof BoardPortalClerkFilingsRoute
  '/board-portal/clerk/minutes': typeof BoardPortalClerkMinutesRoute
  '/board-portal/clerk/policies': typeof BoardPortalClerkPoliciesRoute
  '/board-portal/clerk/records': typeof BoardPortalClerkRecordsRoute
  '/board-portal/clerk/votes': typeof BoardPortalClerkVotesRoute
  '/board-portal/coo/feedback': typeof BoardPortalCooFeedbackRoute
  '/board-portal/coo/gaps': typeof BoardPortalCooGapsRoute
  '/board-portal/ed/audit': typeof BoardPortalEdAuditRoute
  '/board-portal/ed/back-to-school': typeof BoardPortalEdBackToSchoolRoute
  '/board-portal/ed/board': typeof BoardPortalEdBoardRoute
  '/board-portal/ed/documents': typeof BoardPortalEdDocumentsRoute
  '/board-portal/ed/donations': typeof BoardPortalEdDonationsRoute
  '/board-portal/ed/financial-reports': typeof BoardPortalEdFinancialReportsRoute
  '/board-portal/ed/grants': typeof BoardPortalEdGrantsRoute
  '/board-portal/ed/programs': typeof BoardPortalEdProgramsRoute
  '/board-portal/ed/reports': typeof BoardPortalEdReportsRoute
  '/board-portal/ed/settings': typeof BoardPortalEdSettingsRoute
  '/board-portal/ed/staff': typeof BoardPortalEdStaffRoute
  '/board-portal/ed/users': typeof BoardPortalEdUsersRoute
  '/board-portal/ed/volunteers': typeof BoardPortalEdVolunteersRoute
  '/board-portal/ed/website': typeof BoardPortalEdWebsiteRoute
  '/board-portal/events/budgets': typeof BoardPortalEventsBudgetsRoute
  '/board-portal/events/inventory': typeof BoardPortalEventsInventoryRoute
  '/board-portal/events/purchase-requests': typeof BoardPortalEventsPurchaseRequestsRoute
  '/board-portal/events/reimbursements': typeof BoardPortalEventsReimbursementsRoute
  '/board-portal/events/shopping': typeof BoardPortalEventsShoppingRoute
  '/board-portal/events/vendors': typeof BoardPortalEventsVendorsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/board-portal/cfo/': typeof BoardPortalCfoIndexRoute
  '/board-portal/clerk/': typeof BoardPortalClerkIndexRoute
  '/board-portal/coo/': typeof BoardPortalCooIndexRoute
  '/board-portal/ed/': typeof BoardPortalEdIndexRoute
  '/board-portal/events/': typeof BoardPortalEventsIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/back-to-school': typeof BackToSchoolRoute
  '/board': typeof BoardRoute
  '/board-portal': typeof BoardPortalRouteWithChildren
  '/bylaws': typeof BylawsRoute
  '/careers': typeof CareersRoute
  '/chauntaes-voice': typeof ChauntaesVoiceRoute
  '/community-partners': typeof CommunityPartnersRoute
  '/conflict-of-interest': typeof ConflictOfInterestRoute
  '/contact': typeof ContactRoute
  '/corporate-sponsorships': typeof CorporateSponsorshipsRoute
  '/documents': typeof DocumentsRoute
  '/donate': typeof DonateRoute
  '/donation-policy': typeof DonationPolicyRoute
  '/eligibility': typeof EligibilityRoute
  '/faq': typeof FaqRoute
  '/food-drives': typeof FoodDrivesRoute
  '/founder': typeof FounderRoute
  '/governance': typeof GovernanceRoute
  '/hipaa': typeof HipaaRoute
  '/how-funds-are-used': typeof HowFundsAreUsedRoute
  '/impact': typeof ImpactRoute
  '/insurance': typeof InsuranceRoute
  '/login': typeof LoginRoute
  '/nonprofit-status': typeof NonprofitStatusRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/referrals': typeof ReferralsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsor-a-family': typeof SponsorAFamilyRoute
  '/staffing-compensation': typeof StaffingCompensationRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/updates': typeof UpdatesRoute
  '/volunteer-policy': typeof VolunteerPolicyRoute
  '/board-portal/calendar': typeof BoardPortalCalendarRoute
  '/board-portal/documents': typeof BoardPortalDocumentsRoute
  '/board-portal/messages': typeof BoardPortalMessagesRoute
  '/board-portal/notifications': typeof BoardPortalNotificationsRoute
  '/board-portal/tasks': typeof BoardPortalTasksRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/notify-staff': typeof ApiPublicNotifyStaffRoute
  '/board-portal/cfo/budget': typeof BoardPortalCfoBudgetRoute
  '/board-portal/cfo/donations': typeof BoardPortalCfoDonationsRoute
  '/board-portal/cfo/expenses': typeof BoardPortalCfoExpensesRoute
  '/board-portal/cfo/reports': typeof BoardPortalCfoReportsRoute
  '/board-portal/clerk/filings': typeof BoardPortalClerkFilingsRoute
  '/board-portal/clerk/minutes': typeof BoardPortalClerkMinutesRoute
  '/board-portal/clerk/policies': typeof BoardPortalClerkPoliciesRoute
  '/board-portal/clerk/records': typeof BoardPortalClerkRecordsRoute
  '/board-portal/clerk/votes': typeof BoardPortalClerkVotesRoute
  '/board-portal/coo/feedback': typeof BoardPortalCooFeedbackRoute
  '/board-portal/coo/gaps': typeof BoardPortalCooGapsRoute
  '/board-portal/ed/audit': typeof BoardPortalEdAuditRoute
  '/board-portal/ed/back-to-school': typeof BoardPortalEdBackToSchoolRoute
  '/board-portal/ed/board': typeof BoardPortalEdBoardRoute
  '/board-portal/ed/documents': typeof BoardPortalEdDocumentsRoute
  '/board-portal/ed/donations': typeof BoardPortalEdDonationsRoute
  '/board-portal/ed/financial-reports': typeof BoardPortalEdFinancialReportsRoute
  '/board-portal/ed/grants': typeof BoardPortalEdGrantsRoute
  '/board-portal/ed/programs': typeof BoardPortalEdProgramsRoute
  '/board-portal/ed/reports': typeof BoardPortalEdReportsRoute
  '/board-portal/ed/settings': typeof BoardPortalEdSettingsRoute
  '/board-portal/ed/staff': typeof BoardPortalEdStaffRoute
  '/board-portal/ed/users': typeof BoardPortalEdUsersRoute
  '/board-portal/ed/volunteers': typeof BoardPortalEdVolunteersRoute
  '/board-portal/ed/website': typeof BoardPortalEdWebsiteRoute
  '/board-portal/events/budgets': typeof BoardPortalEventsBudgetsRoute
  '/board-portal/events/inventory': typeof BoardPortalEventsInventoryRoute
  '/board-portal/events/purchase-requests': typeof BoardPortalEventsPurchaseRequestsRoute
  '/board-portal/events/reimbursements': typeof BoardPortalEventsReimbursementsRoute
  '/board-portal/events/shopping': typeof BoardPortalEventsShoppingRoute
  '/board-portal/events/vendors': typeof BoardPortalEventsVendorsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/board-portal/cfo': typeof BoardPortalCfoIndexRoute
  '/board-portal/clerk': typeof BoardPortalClerkIndexRoute
  '/board-portal/coo': typeof BoardPortalCooIndexRoute
  '/board-portal/ed': typeof BoardPortalEdIndexRoute
  '/board-portal/events': typeof BoardPortalEventsIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/back-to-school': typeof BackToSchoolRoute
  '/board': typeof BoardRoute
  '/board-portal': typeof BoardPortalRouteWithChildren
  '/bylaws': typeof BylawsRoute
  '/careers': typeof CareersRoute
  '/chauntaes-voice': typeof ChauntaesVoiceRoute
  '/community-partners': typeof CommunityPartnersRoute
  '/conflict-of-interest': typeof ConflictOfInterestRoute
  '/contact': typeof ContactRoute
  '/corporate-sponsorships': typeof CorporateSponsorshipsRoute
  '/documents': typeof DocumentsRoute
  '/donate': typeof DonateRoute
  '/donation-policy': typeof DonationPolicyRoute
  '/eligibility': typeof EligibilityRoute
  '/faq': typeof FaqRoute
  '/food-drives': typeof FoodDrivesRoute
  '/founder': typeof FounderRoute
  '/governance': typeof GovernanceRoute
  '/hipaa': typeof HipaaRoute
  '/how-funds-are-used': typeof HowFundsAreUsedRoute
  '/impact': typeof ImpactRoute
  '/insurance': typeof InsuranceRoute
  '/login': typeof LoginRoute
  '/nonprofit-status': typeof NonprofitStatusRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/referrals': typeof ReferralsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsor-a-family': typeof SponsorAFamilyRoute
  '/staffing-compensation': typeof StaffingCompensationRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/updates': typeof UpdatesRoute
  '/volunteer-policy': typeof VolunteerPolicyRoute
  '/board-portal/calendar': typeof BoardPortalCalendarRoute
  '/board-portal/cfo': typeof BoardPortalCfoRouteWithChildren
  '/board-portal/clerk': typeof BoardPortalClerkRouteWithChildren
  '/board-portal/coo': typeof BoardPortalCooRouteWithChildren
  '/board-portal/documents': typeof BoardPortalDocumentsRoute
  '/board-portal/ed': typeof BoardPortalEdRouteWithChildren
  '/board-portal/events': typeof BoardPortalEventsRouteWithChildren
  '/board-portal/messages': typeof BoardPortalMessagesRoute
  '/board-portal/notifications': typeof BoardPortalNotificationsRoute
  '/board-portal/tasks': typeof BoardPortalTasksRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/notify-staff': typeof ApiPublicNotifyStaffRoute
  '/board-portal/cfo/budget': typeof BoardPortalCfoBudgetRoute
  '/board-portal/cfo/donations': typeof BoardPortalCfoDonationsRoute
  '/board-portal/cfo/expenses': typeof BoardPortalCfoExpensesRoute
  '/board-portal/cfo/reports': typeof BoardPortalCfoReportsRoute
  '/board-portal/clerk/filings': typeof BoardPortalClerkFilingsRoute
  '/board-portal/clerk/minutes': typeof BoardPortalClerkMinutesRoute
  '/board-portal/clerk/policies': typeof BoardPortalClerkPoliciesRoute
  '/board-portal/clerk/records': typeof BoardPortalClerkRecordsRoute
  '/board-portal/clerk/votes': typeof BoardPortalClerkVotesRoute
  '/board-portal/coo/feedback': typeof BoardPortalCooFeedbackRoute
  '/board-portal/coo/gaps': typeof BoardPortalCooGapsRoute
  '/board-portal/ed/audit': typeof BoardPortalEdAuditRoute
  '/board-portal/ed/back-to-school': typeof BoardPortalEdBackToSchoolRoute
  '/board-portal/ed/board': typeof BoardPortalEdBoardRoute
  '/board-portal/ed/documents': typeof BoardPortalEdDocumentsRoute
  '/board-portal/ed/donations': typeof BoardPortalEdDonationsRoute
  '/board-portal/ed/financial-reports': typeof BoardPortalEdFinancialReportsRoute
  '/board-portal/ed/grants': typeof BoardPortalEdGrantsRoute
  '/board-portal/ed/programs': typeof BoardPortalEdProgramsRoute
  '/board-portal/ed/reports': typeof BoardPortalEdReportsRoute
  '/board-portal/ed/settings': typeof BoardPortalEdSettingsRoute
  '/board-portal/ed/staff': typeof BoardPortalEdStaffRoute
  '/board-portal/ed/users': typeof BoardPortalEdUsersRoute
  '/board-portal/ed/volunteers': typeof BoardPortalEdVolunteersRoute
  '/board-portal/ed/website': typeof BoardPortalEdWebsiteRoute
  '/board-portal/events/budgets': typeof BoardPortalEventsBudgetsRoute
  '/board-portal/events/inventory': typeof BoardPortalEventsInventoryRoute
  '/board-portal/events/purchase-requests': typeof BoardPortalEventsPurchaseRequestsRoute
  '/board-portal/events/reimbursements': typeof BoardPortalEventsReimbursementsRoute
  '/board-portal/events/shopping': typeof BoardPortalEventsShoppingRoute
  '/board-portal/events/vendors': typeof BoardPortalEventsVendorsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/board-portal/cfo/': typeof BoardPortalCfoIndexRoute
  '/board-portal/clerk/': typeof BoardPortalClerkIndexRoute
  '/board-portal/coo/': typeof BoardPortalCooIndexRoute
  '/board-portal/ed/': typeof BoardPortalEdIndexRoute
  '/board-portal/events/': typeof BoardPortalEventsIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/back-to-school'
    | '/board'
    | '/board-portal'
    | '/bylaws'
    | '/careers'
    | '/chauntaes-voice'
    | '/community-partners'
    | '/conflict-of-interest'
    | '/contact'
    | '/corporate-sponsorships'
    | '/documents'
    | '/donate'
    | '/donation-policy'
    | '/eligibility'
    | '/faq'
    | '/food-drives'
    | '/founder'
    | '/governance'
    | '/hipaa'
    | '/how-funds-are-used'
    | '/impact'
    | '/insurance'
    | '/login'
    | '/nonprofit-status'
    | '/portal'
    | '/privacy'
    | '/referrals'
    | '/reset-password'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/sponsor-a-family'
    | '/staffing-compensation'
    | '/terms'
    | '/transparency'
    | '/updates'
    | '/volunteer-policy'
    | '/board-portal/calendar'
    | '/board-portal/cfo'
    | '/board-portal/clerk'
    | '/board-portal/coo'
    | '/board-portal/documents'
    | '/board-portal/ed'
    | '/board-portal/events'
    | '/board-portal/messages'
    | '/board-portal/notifications'
    | '/board-portal/tasks'
    | '/email/unsubscribe'
    | '/api/public/notify-staff'
    | '/board-portal/cfo/budget'
    | '/board-portal/cfo/donations'
    | '/board-portal/cfo/expenses'
    | '/board-portal/cfo/reports'
    | '/board-portal/clerk/filings'
    | '/board-portal/clerk/minutes'
    | '/board-portal/clerk/policies'
    | '/board-portal/clerk/records'
    | '/board-portal/clerk/votes'
    | '/board-portal/coo/feedback'
    | '/board-portal/coo/gaps'
    | '/board-portal/ed/audit'
    | '/board-portal/ed/back-to-school'
    | '/board-portal/ed/board'
    | '/board-portal/ed/documents'
    | '/board-portal/ed/donations'
    | '/board-portal/ed/financial-reports'
    | '/board-portal/ed/grants'
    | '/board-portal/ed/programs'
    | '/board-portal/ed/reports'
    | '/board-portal/ed/settings'
    | '/board-portal/ed/staff'
    | '/board-portal/ed/users'
    | '/board-portal/ed/volunteers'
    | '/board-portal/ed/website'
    | '/board-portal/events/budgets'
    | '/board-portal/events/inventory'
    | '/board-portal/events/purchase-requests'
    | '/board-portal/events/reimbursements'
    | '/board-portal/events/shopping'
    | '/board-portal/events/vendors'
    | '/lovable/email/suppression'
    | '/board-portal/cfo/'
    | '/board-portal/clerk/'
    | '/board-portal/coo/'
    | '/board-portal/ed/'
    | '/board-portal/events/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/back-to-school'
    | '/board'
    | '/board-portal'
    | '/bylaws'
    | '/careers'
    | '/chauntaes-voice'
    | '/community-partners'
    | '/conflict-of-interest'
    | '/contact'
    | '/corporate-sponsorships'
    | '/documents'
    | '/donate'
    | '/donation-policy'
    | '/eligibility'
    | '/faq'
    | '/food-drives'
    | '/founder'
    | '/governance'
    | '/hipaa'
    | '/how-funds-are-used'
    | '/impact'
    | '/insurance'
    | '/login'
    | '/nonprofit-status'
    | '/portal'
    | '/privacy'
    | '/referrals'
    | '/reset-password'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/sponsor-a-family'
    | '/staffing-compensation'
    | '/terms'
    | '/transparency'
    | '/updates'
    | '/volunteer-policy'
    | '/board-portal/calendar'
    | '/board-portal/documents'
    | '/board-portal/messages'
    | '/board-portal/notifications'
    | '/board-portal/tasks'
    | '/email/unsubscribe'
    | '/api/public/notify-staff'
    | '/board-portal/cfo/budget'
    | '/board-portal/cfo/donations'
    | '/board-portal/cfo/expenses'
    | '/board-portal/cfo/reports'
    | '/board-portal/clerk/filings'
    | '/board-portal/clerk/minutes'
    | '/board-portal/clerk/policies'
    | '/board-portal/clerk/records'
    | '/board-portal/clerk/votes'
    | '/board-portal/coo/feedback'
    | '/board-portal/coo/gaps'
    | '/board-portal/ed/audit'
    | '/board-portal/ed/back-to-school'
    | '/board-portal/ed/board'
    | '/board-portal/ed/documents'
    | '/board-portal/ed/donations'
    | '/board-portal/ed/financial-reports'
    | '/board-portal/ed/grants'
    | '/board-portal/ed/programs'
    | '/board-portal/ed/reports'
    | '/board-portal/ed/settings'
    | '/board-portal/ed/staff'
    | '/board-portal/ed/users'
    | '/board-portal/ed/volunteers'
    | '/board-portal/ed/website'
    | '/board-portal/events/budgets'
    | '/board-portal/events/inventory'
    | '/board-portal/events/purchase-requests'
    | '/board-portal/events/reimbursements'
    | '/board-portal/events/shopping'
    | '/board-portal/events/vendors'
    | '/lovable/email/suppression'
    | '/board-portal/cfo'
    | '/board-portal/clerk'
    | '/board-portal/coo'
    | '/board-portal/ed'
    | '/board-portal/events'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/back-to-school'
    | '/board'
    | '/board-portal'
    | '/bylaws'
    | '/careers'
    | '/chauntaes-voice'
    | '/community-partners'
    | '/conflict-of-interest'
    | '/contact'
    | '/corporate-sponsorships'
    | '/documents'
    | '/donate'
    | '/donation-policy'
    | '/eligibility'
    | '/faq'
    | '/food-drives'
    | '/founder'
    | '/governance'
    | '/hipaa'
    | '/how-funds-are-used'
    | '/impact'
    | '/insurance'
    | '/login'
    | '/nonprofit-status'
    | '/portal'
    | '/privacy'
    | '/referrals'
    | '/reset-password'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/sponsor-a-family'
    | '/staffing-compensation'
    | '/terms'
    | '/transparency'
    | '/updates'
    | '/volunteer-policy'
    | '/board-portal/calendar'
    | '/board-portal/cfo'
    | '/board-portal/clerk'
    | '/board-portal/coo'
    | '/board-portal/documents'
    | '/board-portal/ed'
    | '/board-portal/events'
    | '/board-portal/messages'
    | '/board-portal/notifications'
    | '/board-portal/tasks'
    | '/email/unsubscribe'
    | '/api/public/notify-staff'
    | '/board-portal/cfo/budget'
    | '/board-portal/cfo/donations'
    | '/board-portal/cfo/expenses'
    | '/board-portal/cfo/reports'
    | '/board-portal/clerk/filings'
    | '/board-portal/clerk/minutes'
    | '/board-portal/clerk/policies'
    | '/board-portal/clerk/records'
    | '/board-portal/clerk/votes'
    | '/board-portal/coo/feedback'
    | '/board-portal/coo/gaps'
    | '/board-portal/ed/audit'
    | '/board-portal/ed/back-to-school'
    | '/board-portal/ed/board'
    | '/board-portal/ed/documents'
    | '/board-portal/ed/donations'
    | '/board-portal/ed/financial-reports'
    | '/board-portal/ed/grants'
    | '/board-portal/ed/programs'
    | '/board-portal/ed/reports'
    | '/board-portal/ed/settings'
    | '/board-portal/ed/staff'
    | '/board-portal/ed/users'
    | '/board-portal/ed/volunteers'
    | '/board-portal/ed/website'
    | '/board-portal/events/budgets'
    | '/board-portal/events/inventory'
    | '/board-portal/events/purchase-requests'
    | '/board-portal/events/reimbursements'
    | '/board-portal/events/shopping'
    | '/board-portal/events/vendors'
    | '/lovable/email/suppression'
    | '/board-portal/cfo/'
    | '/board-portal/clerk/'
    | '/board-portal/coo/'
    | '/board-portal/ed/'
    | '/board-portal/events/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BackToSchoolRoute: typeof BackToSchoolRoute
  BoardRoute: typeof BoardRoute
  BoardPortalRoute: typeof BoardPortalRouteWithChildren
  BylawsRoute: typeof BylawsRoute
  CareersRoute: typeof CareersRoute
  ChauntaesVoiceRoute: typeof ChauntaesVoiceRoute
  CommunityPartnersRoute: typeof CommunityPartnersRoute
  ConflictOfInterestRoute: typeof ConflictOfInterestRoute
  ContactRoute: typeof ContactRoute
  CorporateSponsorshipsRoute: typeof CorporateSponsorshipsRoute
  DocumentsRoute: typeof DocumentsRoute
  DonateRoute: typeof DonateRoute
  DonationPolicyRoute: typeof DonationPolicyRoute
  EligibilityRoute: typeof EligibilityRoute
  FaqRoute: typeof FaqRoute
  FoodDrivesRoute: typeof FoodDrivesRoute
  FounderRoute: typeof FounderRoute
  GovernanceRoute: typeof GovernanceRoute
  HipaaRoute: typeof HipaaRoute
  HowFundsAreUsedRoute: typeof HowFundsAreUsedRoute
  ImpactRoute: typeof ImpactRoute
  InsuranceRoute: typeof InsuranceRoute
  LoginRoute: typeof LoginRoute
  NonprofitStatusRoute: typeof NonprofitStatusRoute
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  ReferralsRoute: typeof ReferralsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SponsorAFamilyRoute: typeof SponsorAFamilyRoute
  StaffingCompensationRoute: typeof StaffingCompensationRoute
  TermsRoute: typeof TermsRoute
  TransparencyRoute: typeof TransparencyRoute
  UpdatesRoute: typeof UpdatesRoute
  VolunteerPolicyRoute: typeof VolunteerPolicyRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicNotifyStaffRoute: typeof ApiPublicNotifyStaffRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer-policy': {
      id: '/volunteer-policy'
      path: '/volunteer-policy'
      fullPath: '/volunteer-policy'
      preLoaderRoute: typeof VolunteerPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staffing-compensation': {
      id: '/staffing-compensation'
      path: '/staffing-compensation'
      fullPath: '/staffing-compensation'
      preLoaderRoute: typeof StaffingCompensationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor-a-family': {
      id: '/sponsor-a-family'
      path: '/sponsor-a-family'
      fullPath: '/sponsor-a-family'
      preLoaderRoute: typeof SponsorAFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nonprofit-status': {
      id: '/nonprofit-status'
      path: '/nonprofit-status'
      fullPath: '/nonprofit-status'
      preLoaderRoute: typeof NonprofitStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-funds-are-used': {
      id: '/how-funds-are-used'
      path: '/how-funds-are-used'
      fullPath: '/how-funds-are-used'
      preLoaderRoute: typeof HowFundsAreUsedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hipaa': {
      id: '/hipaa'
      path: '/hipaa'
      fullPath: '/hipaa'
      preLoaderRoute: typeof HipaaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-drives': {
      id: '/food-drives'
      path: '/food-drives'
      fullPath: '/food-drives'
      preLoaderRoute: typeof FoodDrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donation-policy': {
      id: '/donation-policy'
      path: '/donation-policy'
      fullPath: '/donation-policy'
      preLoaderRoute: typeof DonationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-sponsorships': {
      id: '/corporate-sponsorships'
      path: '/corporate-sponsorships'
      fullPath: '/corporate-sponsorships'
      preLoaderRoute: typeof CorporateSponsorshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflict-of-interest': {
      id: '/conflict-of-interest'
      path: '/conflict-of-interest'
      fullPath: '/conflict-of-interest'
      preLoaderRoute: typeof ConflictOfInterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-partners': {
      id: '/community-partners'
      path: '/community-partners'
      fullPath: '/community-partners'
      preLoaderRoute: typeof CommunityPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauntaes-voice': {
      id: '/chauntaes-voice'
      path: '/chauntaes-voice'
      fullPath: '/chauntaes-voice'
      preLoaderRoute: typeof ChauntaesVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bylaws': {
      id: '/bylaws'
      path: '/bylaws'
      fullPath: '/bylaws'
      preLoaderRoute: typeof BylawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board-portal': {
      id: '/board-portal'
      path: '/board-portal'
      fullPath: '/board-portal'
      preLoaderRoute: typeof BoardPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back-to-school': {
      id: '/back-to-school'
      path: '/back-to-school'
      fullPath: '/back-to-school'
      preLoaderRoute: typeof BackToSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board-portal/tasks': {
      id: '/board-portal/tasks'
      path: '/tasks'
      fullPath: '/board-portal/tasks'
      preLoaderRoute: typeof BoardPortalTasksRouteImport
      parentRoute: typeof BoardPortalRoute
    }
    '/board-portal/notifications': {
      id: '/board-portal/notifications'
      path: '/notifications'
      fullPath: '/board-portal/notifications'
      preLoaderRoute: typeof BoardPortalNotificationsRouteImport
      parentRoute: typeof BoardPortalRoute
    }
    '/board-portal/messages': {
      id: '/board-portal/messages'
      path: '/messages'
      fullPath: '/board-portal/messages'
      preLoaderRoute: typeof BoardPortalMessagesRouteImport
      parentRoute: typeof BoardPortalRoute
    }
    '/board-portal/events': {
      id: '/board-portal/events'
      path: '/events'
      fullPath: '/board-portal/events'
      preLoaderRoute: typeof BoardPortalEventsRouteImport
      parentRoute: typeof BoardPortalRoute
    }
    '/board-portal/ed': {
      id: '/board-portal/ed'
      path: '/ed'
      fullPath: '/board-portal/ed'
      preLoaderRoute: typeof BoardPortalEdRouteImport
      parentRoute: typeof BoardPortalRoute
    }
    '/board-portal/documents': {
      id: '/board-portal/documents'
      path: '/documents'
      fullPath: '/board-portal/documents'
      preLoaderRoute: typeof BoardPortalDocumentsRouteImport
      parentRoute: typeof BoardPortalRoute
    }
    '/board-portal/coo': {
      id: '/board-portal/coo'
      path: '/coo'
      fullPath: '/board-portal/coo'
      preLoaderRoute: typeof BoardPortalCooRouteImport
      parentRoute: typeof BoardPortalRoute
    }
    '/board-portal/clerk': {
      id: '/board-portal/clerk'
      path: '/clerk'
      fullPath: '/board-portal/clerk'
      preLoaderRoute: typeof BoardPortalClerkRouteImport
      parentRoute: typeof BoardPortalRoute
    }
    '/board-portal/cfo': {
      id: '/board-portal/cfo'
      path: '/cfo'
      fullPath: '/board-portal/cfo'
      preLoaderRoute: typeof BoardPortalCfoRouteImport
      parentRoute: typeof BoardPortalRoute
    }
    '/board-portal/calendar': {
      id: '/board-portal/calendar'
      path: '/calendar'
      fullPath: '/board-portal/calendar'
      preLoaderRoute: typeof BoardPortalCalendarRouteImport
      parentRoute: typeof BoardPortalRoute
    }
    '/board-portal/events/': {
      id: '/board-portal/events/'
      path: '/'
      fullPath: '/board-portal/events/'
      preLoaderRoute: typeof BoardPortalEventsIndexRouteImport
      parentRoute: typeof BoardPortalEventsRoute
    }
    '/board-portal/ed/': {
      id: '/board-portal/ed/'
      path: '/'
      fullPath: '/board-portal/ed/'
      preLoaderRoute: typeof BoardPortalEdIndexRouteImport
      parentRoute: typeof BoardPortalEdRoute
    }
    '/board-portal/coo/': {
      id: '/board-portal/coo/'
      path: '/'
      fullPath: '/board-portal/coo/'
      preLoaderRoute: typeof BoardPortalCooIndexRouteImport
      parentRoute: typeof BoardPortalCooRoute
    }
    '/board-portal/clerk/': {
      id: '/board-portal/clerk/'
      path: '/'
      fullPath: '/board-portal/clerk/'
      preLoaderRoute: typeof BoardPortalClerkIndexRouteImport
      parentRoute: typeof BoardPortalClerkRoute
    }
    '/board-portal/cfo/': {
      id: '/board-portal/cfo/'
      path: '/'
      fullPath: '/board-portal/cfo/'
      preLoaderRoute: typeof BoardPortalCfoIndexRouteImport
      parentRoute: typeof BoardPortalCfoRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board-portal/events/vendors': {
      id: '/board-portal/events/vendors'
      path: '/vendors'
      fullPath: '/board-portal/events/vendors'
      preLoaderRoute: typeof BoardPortalEventsVendorsRouteImport
      parentRoute: typeof BoardPortalEventsRoute
    }
    '/board-portal/events/shopping': {
      id: '/board-portal/events/shopping'
      path: '/shopping'
      fullPath: '/board-portal/events/shopping'
      preLoaderRoute: typeof BoardPortalEventsShoppingRouteImport
      parentRoute: typeof BoardPortalEventsRoute
    }
    '/board-portal/events/reimbursements': {
      id: '/board-portal/events/reimbursements'
      path: '/reimbursements'
      fullPath: '/board-portal/events/reimbursements'
      preLoaderRoute: typeof BoardPortalEventsReimbursementsRouteImport
      parentRoute: typeof BoardPortalEventsRoute
    }
    '/board-portal/events/purchase-requests': {
      id: '/board-portal/events/purchase-requests'
      path: '/purchase-requests'
      fullPath: '/board-portal/events/purchase-requests'
      preLoaderRoute: typeof BoardPortalEventsPurchaseRequestsRouteImport
      parentRoute: typeof BoardPortalEventsRoute
    }
    '/board-portal/events/inventory': {
      id: '/board-portal/events/inventory'
      path: '/inventory'
      fullPath: '/board-portal/events/inventory'
      preLoaderRoute: typeof BoardPortalEventsInventoryRouteImport
      parentRoute: typeof BoardPortalEventsRoute
    }
    '/board-portal/events/budgets': {
      id: '/board-portal/events/budgets'
      path: '/budgets'
      fullPath: '/board-portal/events/budgets'
      preLoaderRoute: typeof BoardPortalEventsBudgetsRouteImport
      parentRoute: typeof BoardPortalEventsRoute
    }
    '/board-portal/ed/website': {
      id: '/board-portal/ed/website'
      path: '/website'
      fullPath: '/board-portal/ed/website'
      preLoaderRoute: typeof BoardPortalEdWebsiteRouteImport
      parentRoute: typeof BoardPortalEdRoute
    }
    '/board-portal/ed/volunteers': {
      id: '/board-portal/ed/volunteers'
      path: '/volunteers'
      fullPath: '/board-portal/ed/volunteers'
      preLoaderRoute: typeof BoardPortalEdVolunteersRouteImport
      parentRoute: typeof BoardPortalEdRoute
    }
    '/board-portal/ed/users': {
      id: '/board-portal/ed/users'
      path: '/users'
      fullPath: '/board-portal/ed/users'
      preLoaderRoute: typeof BoardPortalEdUsersRouteImport
      parentRoute: typeof BoardPortalEdRoute
    }
    '/board-portal/ed/staff': {
      id: '/board-portal/ed/staff'
      path: '/staff'
      fullPath: '/board-portal/ed/staff'
      preLoaderRoute: typeof BoardPortalEdStaffRouteImport
      parentRoute: typeof BoardPortalEdRoute
    }
    '/board-portal/ed/settings': {
      id: '/board-portal/ed/settings'
      path: '/settings'
      fullPath: '/board-portal/ed/settings'
      preLoaderRoute: typeof BoardPortalEdSettingsRouteImport
      parentRoute: typeof BoardPortalEdRoute
    }
    '/board-portal/ed/reports': {
      id: '/board-portal/ed/reports'
      path: '/reports'
      fullPath: '/board-portal/ed/reports'
      preLoaderRoute: typeof BoardPortalEdReportsRouteImport
      parentRoute: typeof BoardPortalEdRoute
    }
    '/board-portal/ed/programs': {
      id: '/board-portal/ed/programs'
      path: '/programs'
      fullPath: '/board-portal/ed/programs'
      preLoaderRoute: typeof BoardPortalEdProgramsRouteImport
      parentRoute: typeof BoardPortalEdRoute
    }
    '/board-portal/ed/grants': {
      id: '/board-portal/ed/grants'
      path: '/grants'
      fullPath: '/board-portal/ed/grants'
      preLoaderRoute: typeof BoardPortalEdGrantsRouteImport
      parentRoute: typeof BoardPortalEdRoute
    }
    '/board-portal/ed/financial-reports': {
      id: '/board-portal/ed/financial-reports'
      path: '/financial-reports'
      fullPath: '/board-portal/ed/financial-reports'
      preLoaderRoute: typeof BoardPortalEdFinancialReportsRouteImport
      parentRoute: typeof BoardPortalEdRoute
    }
    '/board-portal/ed/donations': {
      id: '/board-portal/ed/donations'
      path: '/donations'
      fullPath: '/board-portal/ed/donations'
      preLoaderRoute: typeof BoardPortalEdDonationsRouteImport
      parentRoute: typeof BoardPortalEdRoute
    }
    '/board-portal/ed/documents': {
      id: '/board-portal/ed/documents'
      path: '/documents'
      fullPath: '/board-portal/ed/documents'
      preLoaderRoute: typeof BoardPortalEdDocumentsRouteImport
      parentRoute: typeof BoardPortalEdRoute
    }
    '/board-portal/ed/board': {
      id: '/board-portal/ed/board'
      path: '/board'
      fullPath: '/board-portal/ed/board'
      preLoaderRoute: typeof BoardPortalEdBoardRouteImport
      parentRoute: typeof BoardPortalEdRoute
    }
    '/board-portal/ed/back-to-school': {
      id: '/board-portal/ed/back-to-school'
      path: '/back-to-school'
      fullPath: '/board-portal/ed/back-to-school'
      preLoaderRoute: typeof BoardPortalEdBackToSchoolRouteImport
      parentRoute: typeof BoardPortalEdRoute
    }
    '/board-portal/ed/audit': {
      id: '/board-portal/ed/audit'
      path: '/audit'
      fullPath: '/board-portal/ed/audit'
      preLoaderRoute: typeof BoardPortalEdAuditRouteImport
      parentRoute: typeof BoardPortalEdRoute
    }
    '/board-portal/coo/gaps': {
      id: '/board-portal/coo/gaps'
      path: '/gaps'
      fullPath: '/board-portal/coo/gaps'
      preLoaderRoute: typeof BoardPortalCooGapsRouteImport
      parentRoute: typeof BoardPortalCooRoute
    }
    '/board-portal/coo/feedback': {
      id: '/board-portal/coo/feedback'
      path: '/feedback'
      fullPath: '/board-portal/coo/feedback'
      preLoaderRoute: typeof BoardPortalCooFeedbackRouteImport
      parentRoute: typeof BoardPortalCooRoute
    }
    '/board-portal/clerk/votes': {
      id: '/board-portal/clerk/votes'
      path: '/votes'
      fullPath: '/board-portal/clerk/votes'
      preLoaderRoute: typeof BoardPortalClerkVotesRouteImport
      parentRoute: typeof BoardPortalClerkRoute
    }
    '/board-portal/clerk/records': {
      id: '/board-portal/clerk/records'
      path: '/records'
      fullPath: '/board-portal/clerk/records'
      preLoaderRoute: typeof BoardPortalClerkRecordsRouteImport
      parentRoute: typeof BoardPortalClerkRoute
    }
    '/board-portal/clerk/policies': {
      id: '/board-portal/clerk/policies'
      path: '/policies'
      fullPath: '/board-portal/clerk/policies'
      preLoaderRoute: typeof BoardPortalClerkPoliciesRouteImport
      parentRoute: typeof BoardPortalClerkRoute
    }
    '/board-portal/clerk/minutes': {
      id: '/board-portal/clerk/minutes'
      path: '/minutes'
      fullPath: '/board-portal/clerk/minutes'
      preLoaderRoute: typeof BoardPortalClerkMinutesRouteImport
      parentRoute: typeof BoardPortalClerkRoute
    }
    '/board-portal/clerk/filings': {
      id: '/board-portal/clerk/filings'
      path: '/filings'
      fullPath: '/board-portal/clerk/filings'
      preLoaderRoute: typeof BoardPortalClerkFilingsRouteImport
      parentRoute: typeof BoardPortalClerkRoute
    }
    '/board-portal/cfo/reports': {
      id: '/board-portal/cfo/reports'
      path: '/reports'
      fullPath: '/board-portal/cfo/reports'
      preLoaderRoute: typeof BoardPortalCfoReportsRouteImport
      parentRoute: typeof BoardPortalCfoRoute
    }
    '/board-portal/cfo/expenses': {
      id: '/board-portal/cfo/expenses'
      path: '/expenses'
      fullPath: '/board-portal/cfo/expenses'
      preLoaderRoute: typeof BoardPortalCfoExpensesRouteImport
      parentRoute: typeof BoardPortalCfoRoute
    }
    '/board-portal/cfo/donations': {
      id: '/board-portal/cfo/donations'
      path: '/donations'
      fullPath: '/board-portal/cfo/donations'
      preLoaderRoute: typeof BoardPortalCfoDonationsRouteImport
      parentRoute: typeof BoardPortalCfoRoute
    }
    '/board-portal/cfo/budget': {
      id: '/board-portal/cfo/budget'
      path: '/budget'
      fullPath: '/board-portal/cfo/budget'
      preLoaderRoute: typeof BoardPortalCfoBudgetRouteImport
      parentRoute: typeof BoardPortalCfoRoute
    }
    '/api/public/notify-staff': {
      id: '/api/public/notify-staff'
      path: '/api/public/notify-staff'
      fullPath: '/api/public/notify-staff'
      preLoaderRoute: typeof ApiPublicNotifyStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BoardPortalCfoRouteChildren {
  BoardPortalCfoBudgetRoute: typeof BoardPortalCfoBudgetRoute
  BoardPortalCfoDonationsRoute: typeof BoardPortalCfoDonationsRoute
  BoardPortalCfoExpensesRoute: typeof BoardPortalCfoExpensesRoute
  BoardPortalCfoReportsRoute: typeof BoardPortalCfoReportsRoute
  BoardPortalCfoIndexRoute: typeof BoardPortalCfoIndexRoute
}

const BoardPortalCfoRouteChildren: BoardPortalCfoRouteChildren = {
  BoardPortalCfoBudgetRoute: BoardPortalCfoBudgetRoute,
  BoardPortalCfoDonationsRoute: BoardPortalCfoDonationsRoute,
  BoardPortalCfoExpensesRoute: BoardPortalCfoExpensesRoute,
  BoardPortalCfoReportsRoute: BoardPortalCfoReportsRoute,
  BoardPortalCfoIndexRoute: BoardPortalCfoIndexRoute,
}

const BoardPortalCfoRouteWithChildren = BoardPortalCfoRoute._addFileChildren(
  BoardPortalCfoRouteChildren,
)

interface BoardPortalClerkRouteChildren {
  BoardPortalClerkFilingsRoute: typeof BoardPortalClerkFilingsRoute
  BoardPortalClerkMinutesRoute: typeof BoardPortalClerkMinutesRoute
  BoardPortalClerkPoliciesRoute: typeof BoardPortalClerkPoliciesRoute
  BoardPortalClerkRecordsRoute: typeof BoardPortalClerkRecordsRoute
  BoardPortalClerkVotesRoute: typeof BoardPortalClerkVotesRoute
  BoardPortalClerkIndexRoute: typeof BoardPortalClerkIndexRoute
}

const BoardPortalClerkRouteChildren: BoardPortalClerkRouteChildren = {
  BoardPortalClerkFilingsRoute: BoardPortalClerkFilingsRoute,
  BoardPortalClerkMinutesRoute: BoardPortalClerkMinutesRoute,
  BoardPortalClerkPoliciesRoute: BoardPortalClerkPoliciesRoute,
  BoardPortalClerkRecordsRoute: BoardPortalClerkRecordsRoute,
  BoardPortalClerkVotesRoute: BoardPortalClerkVotesRoute,
  BoardPortalClerkIndexRoute: BoardPortalClerkIndexRoute,
}

const BoardPortalClerkRouteWithChildren =
  BoardPortalClerkRoute._addFileChildren(BoardPortalClerkRouteChildren)

interface BoardPortalCooRouteChildren {
  BoardPortalCooFeedbackRoute: typeof BoardPortalCooFeedbackRoute
  BoardPortalCooGapsRoute: typeof BoardPortalCooGapsRoute
  BoardPortalCooIndexRoute: typeof BoardPortalCooIndexRoute
}

const BoardPortalCooRouteChildren: BoardPortalCooRouteChildren = {
  BoardPortalCooFeedbackRoute: BoardPortalCooFeedbackRoute,
  BoardPortalCooGapsRoute: BoardPortalCooGapsRoute,
  BoardPortalCooIndexRoute: BoardPortalCooIndexRoute,
}

const BoardPortalCooRouteWithChildren = BoardPortalCooRoute._addFileChildren(
  BoardPortalCooRouteChildren,
)

interface BoardPortalEdRouteChildren {
  BoardPortalEdAuditRoute: typeof BoardPortalEdAuditRoute
  BoardPortalEdBackToSchoolRoute: typeof BoardPortalEdBackToSchoolRoute
  BoardPortalEdBoardRoute: typeof BoardPortalEdBoardRoute
  BoardPortalEdDocumentsRoute: typeof BoardPortalEdDocumentsRoute
  BoardPortalEdDonationsRoute: typeof BoardPortalEdDonationsRoute
  BoardPortalEdFinancialReportsRoute: typeof BoardPortalEdFinancialReportsRoute
  BoardPortalEdGrantsRoute: typeof BoardPortalEdGrantsRoute
  BoardPortalEdProgramsRoute: typeof BoardPortalEdProgramsRoute
  BoardPortalEdReportsRoute: typeof BoardPortalEdReportsRoute
  BoardPortalEdSettingsRoute: typeof BoardPortalEdSettingsRoute
  BoardPortalEdStaffRoute: typeof BoardPortalEdStaffRoute
  BoardPortalEdUsersRoute: typeof BoardPortalEdUsersRoute
  BoardPortalEdVolunteersRoute: typeof BoardPortalEdVolunteersRoute
  BoardPortalEdWebsiteRoute: typeof BoardPortalEdWebsiteRoute
  BoardPortalEdIndexRoute: typeof BoardPortalEdIndexRoute
}

const BoardPortalEdRouteChildren: BoardPortalEdRouteChildren = {
  BoardPortalEdAuditRoute: BoardPortalEdAuditRoute,
  BoardPortalEdBackToSchoolRoute: BoardPortalEdBackToSchoolRoute,
  BoardPortalEdBoardRoute: BoardPortalEdBoardRoute,
  BoardPortalEdDocumentsRoute: BoardPortalEdDocumentsRoute,
  BoardPortalEdDonationsRoute: BoardPortalEdDonationsRoute,
  BoardPortalEdFinancialReportsRoute: BoardPortalEdFinancialReportsRoute,
  BoardPortalEdGrantsRoute: BoardPortalEdGrantsRoute,
  BoardPortalEdProgramsRoute: BoardPortalEdProgramsRoute,
  BoardPortalEdReportsRoute: BoardPortalEdReportsRoute,
  BoardPortalEdSettingsRoute: BoardPortalEdSettingsRoute,
  BoardPortalEdStaffRoute: BoardPortalEdStaffRoute,
  BoardPortalEdUsersRoute: BoardPortalEdUsersRoute,
  BoardPortalEdVolunteersRoute: BoardPortalEdVolunteersRoute,
  BoardPortalEdWebsiteRoute: BoardPortalEdWebsiteRoute,
  BoardPortalEdIndexRoute: BoardPortalEdIndexRoute,
}

const BoardPortalEdRouteWithChildren = BoardPortalEdRoute._addFileChildren(
  BoardPortalEdRouteChildren,
)

interface BoardPortalEventsRouteChildren {
  BoardPortalEventsBudgetsRoute: typeof BoardPortalEventsBudgetsRoute
  BoardPortalEventsInventoryRoute: typeof BoardPortalEventsInventoryRoute
  BoardPortalEventsPurchaseRequestsRoute: typeof BoardPortalEventsPurchaseRequestsRoute
  BoardPortalEventsReimbursementsRoute: typeof BoardPortalEventsReimbursementsRoute
  BoardPortalEventsShoppingRoute: typeof BoardPortalEventsShoppingRoute
  BoardPortalEventsVendorsRoute: typeof BoardPortalEventsVendorsRoute
  BoardPortalEventsIndexRoute: typeof BoardPortalEventsIndexRoute
}

const BoardPortalEventsRouteChildren: BoardPortalEventsRouteChildren = {
  BoardPortalEventsBudgetsRoute: BoardPortalEventsBudgetsRoute,
  BoardPortalEventsInventoryRoute: BoardPortalEventsInventoryRoute,
  BoardPortalEventsPurchaseRequestsRoute:
    BoardPortalEventsPurchaseRequestsRoute,
  BoardPortalEventsReimbursementsRoute: BoardPortalEventsReimbursementsRoute,
  BoardPortalEventsShoppingRoute: BoardPortalEventsShoppingRoute,
  BoardPortalEventsVendorsRoute: BoardPortalEventsVendorsRoute,
  BoardPortalEventsIndexRoute: BoardPortalEventsIndexRoute,
}

const BoardPortalEventsRouteWithChildren =
  BoardPortalEventsRoute._addFileChildren(BoardPortalEventsRouteChildren)

interface BoardPortalRouteChildren {
  BoardPortalCalendarRoute: typeof BoardPortalCalendarRoute
  BoardPortalCfoRoute: typeof BoardPortalCfoRouteWithChildren
  BoardPortalClerkRoute: typeof BoardPortalClerkRouteWithChildren
  BoardPortalCooRoute: typeof BoardPortalCooRouteWithChildren
  BoardPortalDocumentsRoute: typeof BoardPortalDocumentsRoute
  BoardPortalEdRoute: typeof BoardPortalEdRouteWithChildren
  BoardPortalEventsRoute: typeof BoardPortalEventsRouteWithChildren
  BoardPortalMessagesRoute: typeof BoardPortalMessagesRoute
  BoardPortalNotificationsRoute: typeof BoardPortalNotificationsRoute
  BoardPortalTasksRoute: typeof BoardPortalTasksRoute
}

const BoardPortalRouteChildren: BoardPortalRouteChildren = {
  BoardPortalCalendarRoute: BoardPortalCalendarRoute,
  BoardPortalCfoRoute: BoardPortalCfoRouteWithChildren,
  BoardPortalClerkRoute: BoardPortalClerkRouteWithChildren,
  BoardPortalCooRoute: BoardPortalCooRouteWithChildren,
  BoardPortalDocumentsRoute: BoardPortalDocumentsRoute,
  BoardPortalEdRoute: BoardPortalEdRouteWithChildren,
  BoardPortalEventsRoute: BoardPortalEventsRouteWithChildren,
  BoardPortalMessagesRoute: BoardPortalMessagesRoute,
  BoardPortalNotificationsRoute: BoardPortalNotificationsRoute,
  BoardPortalTasksRoute: BoardPortalTasksRoute,
}

const BoardPortalRouteWithChildren = BoardPortalRoute._addFileChildren(
  BoardPortalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BackToSchoolRoute: BackToSchoolRoute,
  BoardRoute: BoardRoute,
  BoardPortalRoute: BoardPortalRouteWithChildren,
  BylawsRoute: BylawsRoute,
  CareersRoute: CareersRoute,
  ChauntaesVoiceRoute: ChauntaesVoiceRoute,
  CommunityPartnersRoute: CommunityPartnersRoute,
  ConflictOfInterestRoute: ConflictOfInterestRoute,
  ContactRoute: ContactRoute,
  CorporateSponsorshipsRoute: CorporateSponsorshipsRoute,
  DocumentsRoute: DocumentsRoute,
  DonateRoute: DonateRoute,
  DonationPolicyRoute: DonationPolicyRoute,
  EligibilityRoute: EligibilityRoute,
  FaqRoute: FaqRoute,
  FoodDrivesRoute: FoodDrivesRoute,
  FounderRoute: FounderRoute,
  GovernanceRoute: GovernanceRoute,
  HipaaRoute: HipaaRoute,
  HowFundsAreUsedRoute: HowFundsAreUsedRoute,
  ImpactRoute: ImpactRoute,
  InsuranceRoute: InsuranceRoute,
  LoginRoute: LoginRoute,
  NonprofitStatusRoute: NonprofitStatusRoute,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  ReferralsRoute: ReferralsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SponsorAFamilyRoute: SponsorAFamilyRoute,
  StaffingCompensationRoute: StaffingCompensationRoute,
  TermsRoute: TermsRoute,
  TransparencyRoute: TransparencyRoute,
  UpdatesRoute: UpdatesRoute,
  VolunteerPolicyRoute: VolunteerPolicyRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicNotifyStaffRoute: ApiPublicNotifyStaffRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
